# Generated by Django 5.0.3 on 2024-03-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('yearsexper', models.IntegerField(verbose_name='Опыт работы пользователя')),
                ('projectfinish', models.IntegerField(verbose_name='Проекты завершенный')),
                ('happyclients', models.IntegerField(verbose_name='Счастливые клиенты')),
            ],
            options={
                'verbose_name': 'Доп информации пользователя',
                'verbose_name_plural': 'Доп информации пользователей',
            },
        ),
    ]
