# Generated by Django 5.0.3 on 2024-03-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Теги пользователя', 'verbose_name_plural': 'Теги пользователей'},
        ),
    ]
