# Generated by Django 4.2.11 on 2024-03-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_delete_comments_delete_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleagues',
            name='description',
            field=models.CharField(max_length=255, verbose_name='О коллеге Как он помогает?'),
        ),
    ]
