# Generated by Django 5.0.3 on 2024-03-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователей'},
        ),
        migrations.AddField(
            model_name='infouser',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
