# Generated by Django 5.0.3 on 2024-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_infouser_options_infouser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='email',
            field=models.CharField(default=1, max_length=255, verbose_name='Почта пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='image',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='skills',
            field=models.CharField(default=1, max_length=255, verbose_name='Каким образом пользователь делвает работу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='work',
            field=models.CharField(default=1, max_length=255, verbose_name='Профессия пользователя'),
            preserve_default=False,
        ),
    ]
