# Generated by Django 5.0.3 on 2024-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_infouser_email_infouser_image_infouser_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Почта пользователя'),
        ),
    ]
