# Generated by Django 5.0.3 on 2024-03-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_myservices_alter_infouser_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='myservices',
            name='image',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Проекты пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myservices',
            name='numberpro',
            field=models.IntegerField(default=1, verbose_name='Какой проект'),
            preserve_default=False,
        ),
    ]
