# Generated by Django 5.0.3 on 2024-03-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_myservices_numberpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namepro', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('aboutpro', models.CharField(max_length=255, verbose_name='Коротко о проекте')),
                ('image', models.ImageField(upload_to='info_user/', verbose_name='Проекты пользователя')),
            ],
        ),
        migrations.RemoveField(
            model_name='myservices',
            name='image',
        ),
    ]
