# Generated by Django 5.0.3 on 2024-03-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_project_remove_myservices_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проекты пользователя', 'verbose_name_plural': 'Проекты пользователей'},
        ),
    ]
