# Generated by Django 5.0.3 on 2024-03-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='years',
            new_name='time',
        ),
    ]
