# Generated by Django 5.0.3 on 2024-03-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_years_skills_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_course', models.CharField(max_length=255, verbose_name='Когда обучался')),
                ('where_study', models.CharField(max_length=255, verbose_name='Где учился')),
                ('course_name', models.CharField(max_length=255, verbose_name='В каком курсе или университе училя')),
            ],
            options={
                'verbose_name': 'Обучение пользователя',
                'verbose_name_plural': 'Обучение пользователей',
            },
        ),
    ]
