# Generated by Django 5.0.3 on 2024-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Android',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('about_project', models.CharField(max_length=255, verbose_name='Коротко о проекте')),
                ('image_project', models.ImageField(upload_to='android/', verbose_name='Фотография проекта')),
            ],
            options={
                'verbose_name': 'Android проект пользователя',
                'verbose_name_plural': 'Android проекты пользователей',
            },
        ),
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('about_project', models.CharField(max_length=255, verbose_name='Коротко о проекте')),
                ('image_project', models.ImageField(upload_to='backend/', verbose_name='Фотография проекта')),
            ],
            options={
                'verbose_name': 'Backend проект пользователя',
                'verbose_name_plural': 'Backend проекты пользователей',
            },
        ),
        migrations.CreateModel(
            name='Desinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('about_project', models.CharField(max_length=255, verbose_name='Коротко о проекте')),
                ('image_project', models.ImageField(upload_to='desinger/', verbose_name='Фотография проекта')),
            ],
            options={
                'verbose_name': 'Desinger проект пользователя',
                'verbose_name_plural': 'Desinger проекты пользователей',
            },
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('about_project', models.CharField(max_length=255, verbose_name='Коротко о проекте')),
                ('image_project', models.ImageField(upload_to='frontend/', verbose_name='Фотография проекта')),
            ],
            options={
                'verbose_name': 'Frontend проект пользователя',
                'verbose_name_plural': 'Frontend проекты пользователей',
            },
        ),
        migrations.DeleteModel(
            name='MyServices',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project/', verbose_name='Проекты пользователя'),
        ),
    ]
