# Generated by Django 5.0.3 on 2024-03-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_android_backend_desinger_frontend_delete_myservices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_job', models.CharField(max_length=255, verbose_name='Тип работы')),
                ('number_service', models.IntegerField(verbose_name='Номер работы (порядок)')),
                ('aboutproj', models.CharField(max_length=255, verbose_name='Коротко как он делает роботу')),
            ],
            options={
                'verbose_name': 'Сервис пользователя',
                'verbose_name_plural': 'Сервисы пользоватлей',
            },
        ),
    ]
