# Generated by Django 5.0.3 on 2024-03-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_myservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
