# Generated by Django 5.0.3 on 2024-03-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_android_type_dev_backend_type_dev_desinger_type_dev_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersentShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_thing', models.CharField(max_length=255, verbose_name='Какие библиотеки или фреймфорки он знает')),
                ('persent', models.CharField(max_length=255, verbose_name='На сколько процентов знает')),
            ],
            options={
                'verbose_name': 'Фреймфорки и скилы пользователя',
                'verbose_name_plural': 'Фреймфорки и скилы пользователей',
            },
        ),
    ]
