# Generated by Django 5.0.3 on 2024-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_persentshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='persentshow',
            name='logo',
            field=models.ImageField(default=1, upload_to='persent_show/', verbose_name='Логотип фреймфорка'),
            preserve_default=False,
        ),
    ]
