# Generated by Django 5.0.3 on 2024-03-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_persentshow_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя коллеги')),
                ('company', models.CharField(max_length=255, verbose_name='В каком компании работает')),
                ('photo', models.ImageField(upload_to='colleagues/', verbose_name='Фото коллеги')),
                ('description', models.CharField(max_length=255, verbose_name='О коллеге (Как он вам помогает)')),
            ],
            options={
                'verbose_name': 'Информация о пользователя',
                'verbose_name_plural': 'Информация о пользователей',
            },
        ),
    ]
