# Generated by Django 5.0.3 on 2024-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_colleagues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colleagues',
            options={'verbose_name': 'Информация о коллег', 'verbose_name_plural': 'Информация о коллег'},
        ),
        migrations.AddField(
            model_name='colleagues',
            name='degree',
            field=models.CharField(default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
