# Generated by Django 5.0.3 on 2024-03-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_colleagues_options_colleagues_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleagues',
            name='logo',
            field=models.ImageField(default=1, upload_to='colleagues/', verbose_name='Логотип направлении'),
            preserve_default=False,
        ),
    ]
