# Generated by Django 5.0.3 on 2024-03-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_colleagues_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colleagues',
            name='logo',
        ),
        migrations.AddField(
            model_name='infouser',
            name='adress',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='phone_number',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
