# Generated by Django 5.0.3 on 2024-03-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_colleagues_logo_infouser_adress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Android',
        ),
        migrations.DeleteModel(
            name='Backend',
        ),
        migrations.DeleteModel(
            name='Desinger',
        ),
        migrations.DeleteModel(
            name='Frontend',
        ),
    ]
