# Generated by Django 5.0.3 on 2024-03-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_delete_android_delete_backend_delete_desinger_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colleagues',
        ),
    ]
