# Generated by Django 5.0.3 on 2024-03-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_delete_colleagues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(max_length=255, verbose_name='Имя вашего блога')),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='Фото блога')),
                ('data', models.DateField(verbose_name='Дата вашего блога')),
            ],
        ),
    ]
