# Generated by Django 5.0.3 on 2024-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Блоги пользователя', 'verbose_name_plural': 'Блоги пользователей'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='comments',
            field=models.CharField(default=1, max_length=255, verbose_name='Комментарии'),
            preserve_default=False,
        ),
    ]
