# Generated by Django 5.0.3 on 2024-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_blogs_options_blogs_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(default=1, max_length=255, verbose_name='Категория блога (Tutirial, Tips)'),
            preserve_default=False,
        ),
    ]
