# Generated by Django 5.0.3 on 2024-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_blogs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='update',
            field=models.CharField(default=1, max_length=255, verbose_name='Чего нового'),
            preserve_default=False,
        ),
    ]
