# Generated by Django 5.0.3 on 2024-03-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
