# Generated by Django 5.0.3 on 2024-03-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_blogs_category_remove_blogs_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='data',
        ),
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
