# Generated by Django 5.0.3 on 2024-03-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_blogs_data_blogs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
